### ISSUE TITLE
In the login process, a crash occurs with the previous server

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/dhis2-android-eventcapture#101]

**Comment by idelcano** [comment]
Looks a bad db migration. 

In previous2 the last programstagedataelement(jOfuwos6S28) contains a dataelement uid, but in previous1 is null:
https://play.dhis2.org/android-previous2/api/programStages/v74Hp99bC31
https://play.dhis2.org/android-previous1/api/programStages/v74Hp99bC31

But i will upload a PR ignoring the null dataelements.
