### ISSUE TITLE
Programme rule to hide data elements is not working in 2.26

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-eventcapture#26]
On Android Event Capture app, the hide data element program rule is not working on 2.26.
For example: Program = Antenatal Care Visit, Org unit = Ngelehun CHC, program rule = 'hide smoking cessation counselling dataelement unless patient is smoking.' The initial screen on the android shows all data elements, including the smoking cessation counselling data element that should be hidden. Selecting yes or no for smoking does not result in the data element being hidden.
For the same dataset above, the hide program rule does work on 2.25.
Another example: program = inpatient morbidity and mortality; program rule = hide pregnant if gender is male. Selecting male from the dropdown does not result in the pregnant question disappearing.

**Comment by idelcano** [comment]
@ifoche  the first program rule works perfect, and the second doesn't exist. I tested it in 2.25 2.26 and 2.27
