### ISSUE TITLE
Implement "Completed events expiry days"

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-eventcapture#75]
This feature should avoid user for edit events if the completed events expiry days is over. A pop-up should alert the user

**Comment by idelcano** [comment]
this issue is started in this branch: https://github.com/EyeSeeTea/dhis2-android-sdk/tree/legacy-event-add_completion_expiry_date

**Comment by xurxodev** [comment]
@idelcano @ifoche I have create a issue related with completion date and api in jira https://jira.dhis2.org/browse/DHIS2-2477
